version: '3.1'

services:
    node:
        image: node:14-alpine
        restart: unless-stopped
        working_dir: /var/lib/ghost/content/themes/kikiguru
        volumes:
            - .:/var/lib/ghost/content/themes/kikiguru
        command:
            - yarn
            - dev
    ghost:
        image: ghost:3-alpine
        restart: unless-stopped
        volumes:
            - .:/var/lib/ghost/content/themes/kikiguru
        ports:
            - 8080:2368
        environment:
            NODE_ENV: development
            # see https://docs.ghost.org/docs/config#section-running-ghost-with-config-env-variables
            database__client: mysql
            database__connection__host: mariadb
            database__connection__user: root
            database__connection__password: example
            database__connection__database: ghost
            # this url value is just an example, and is likely wrong for your environment!
            url: http://localhost:8080

    mariadb:
        image: mariadb:10.3
        environment:
            MYSQL_ROOT_PASSWORD: example
