version: '3.1'

services:
    node:
        image: node:18-alpine
        restart: unless-stopped
        working_dir: /var/lib/ghost/content/themes/kikiuru-blog
        volumes:
            - .:/var/lib/ghost/content/themes/kikiuru-blog
        command:
            - yarn
            - dev
    ghost:
        image: ghost:5-alpine
        restart: always
        volumes:
            - .:/var/lib/ghost/content/themes/kikiuru-blog
            - ./.images:/var/lib/ghost/content/images
        ports:
            - 2368:2368
        environment:
            NODE_ENV: development
            database__client: mysql
            database__connection__host: mariadb
            database__connection__user: root
            database__connection__password: root
            database__connection__database: ghost
            # this url value is just an example, and is likely wrong for your environment!
            url: http://localhost:2368
    mariadb:
        image: mariadb:10.6.8
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=ghost
        volumes:
            - mariadb_data:/var/lib/mysql
volumes:
    mariadb_data:
